name: endless-gaming
region: nyc1

# No long-running services needed - using scheduled cron jobs instead

# Database configuration
databases:
  - engine: PG
    name: endless-gaming-db
    num_nodes: 1
    size: db-s-dev-database
    version: "15"

# Jobs for database setup and scheduled tasks
jobs:
  - name: database-setup
    kind: PRE_DEPLOY
    source_dir: /
    environment_slug: python
    
    build_command: |
      pip install poetry
      poetry config virtualenvs.create false
      poetry install --only=main
    
    run_command: |
      python scripts/setup_db.py
    
    envs:
      - key: DATABASE_URL
        scope: RUN_TIME
        value: ${endless-gaming-db.DATABASE_URL}
      - key: PYTHONPATH
        scope: RUN_AND_BUILD_TIME
        value: /app
    
    instance_count: 1
    instance_size_slug: basic-xxs

  - name: daily-data-collection
    kind: CRON
    schedule: "0 6 * * *"  # Run daily at 6 AM UTC
    source_dir: /
    environment_slug: python
    
    build_command: |
      pip install poetry
      poetry config virtualenvs.create false
      poetry install --only=main
    
    run_command: |
      python scripts/collect_games.py collect --max-pages 15
    
    envs:
      - key: DATABASE_URL
        scope: RUN_TIME
        value: ${endless-gaming-db.DATABASE_URL}
      - key: PYTHONPATH
        scope: RUN_AND_BUILD_TIME
        value: /app
      - key: MAX_WORKERS
        scope: RUN_TIME
        value: "3"
    
    instance_count: 1
    instance_size_slug: basic-xs