name: endless-gaming
region: nyc1

# Full-stack deployment with Flask API and Angular frontend

# Services configuration
services:
  # Flask API backend
  - name: backend-api
    source_dir: /endless-gaming-backend
    github:
      repo: YOUR_GITHUB_USERNAME/endless-gaming
      branch: main
    environment_slug: python
    
    build_command: |
      pip install poetry
      poetry config virtualenvs.create false
      poetry install --only=main
      pip install gunicorn
    
    run_command: |
      gunicorn --bind 0.0.0.0:$PORT --workers 2 'app:create_app()'
    
    envs:
      - key: DATABASE_URL
        scope: RUN_TIME
        value: ${endless-gaming-db.DATABASE_URL}
      - key: PYTHONPATH
        scope: RUN_AND_BUILD_TIME
        value: /app
      - key: FLASK_ENV
        scope: RUN_TIME
        value: production
      - key: CORS_ORIGINS
        scope: RUN_TIME
        value: "*"
    
    health_check:
      http_path: /health
      initial_delay_seconds: 30
      period_seconds: 10
      timeout_seconds: 5
      
    http_port: 80
    instance_count: 1
    instance_size_slug: basic-xxs
    
    routes:
      - path: /api
        preserve_path_prefix: false

# Static site configuration for Angular frontend
static_sites:
  - name: frontend-app
    source_dir: /endless-gaming-frontend
    github:
      repo: YOUR_GITHUB_USERNAME/endless-gaming
      branch: main
    environment_slug: node-js
    
    build_command: |
      chmod +x /app/endless-gaming-frontend/.do/build.sh
      /app/endless-gaming-frontend/.do/build.sh
    
    output_dir: /dist
    index_document: index.html
    error_document: index.html
    catchall_document: index.html
    
    routes:
      - path: /

# Database configuration
databases:
  - engine: PG
    name: endless-gaming-db
    num_nodes: 1
    size: db-s-dev-database
    version: "15"

# Jobs for database setup and scheduled tasks
jobs:
  - name: database-setup
    kind: PRE_DEPLOY
    source_dir: /endless-gaming-backend
    environment_slug: python
    
    build_command: |
      pip install poetry
      poetry config virtualenvs.create false
      poetry install --only=main
    
    run_command: |
      python scripts/setup_db.py
    
    envs:
      - key: DATABASE_URL
        scope: RUN_TIME
        value: ${endless-gaming-db.DATABASE_URL}
      - key: PYTHONPATH
        scope: RUN_AND_BUILD_TIME
        value: /app
    
    instance_count: 1
    instance_size_slug: basic-xxs

  - name: daily-data-collection
    kind: CRON
    schedule: "0 6 * * *"  # Run daily at 6 AM UTC
    source_dir: /endless-gaming-backend
    environment_slug: python
    
    build_command: |
      pip install poetry
      poetry config virtualenvs.create false
      poetry install --only=main
    
    run_command: |
      python scripts/collect_games.py collect --max-pages 15
    
    envs:
      - key: DATABASE_URL
        scope: RUN_TIME
        value: ${endless-gaming-db.DATABASE_URL}
      - key: PYTHONPATH
        scope: RUN_AND_BUILD_TIME
        value: /app
      - key: MAX_WORKERS
        scope: RUN_TIME
        value: "3"
    
    instance_count: 1
    instance_size_slug: basic-xs