name: endless-gaming-app
region: nyc1

# Full-stack deployment with Flask API and Angular frontend

# Services configuration
services:
  # Flask API backend
  - name: backend-api
    source_dir: endless-gaming-backend
    github:
      repo: tomneyland/endless-gaming
      branch: master
      deploy_on_push: true
    dockerfile_path: endless-gaming-backend/Dockerfile
    
    envs:
      - key: DATABASE_URL
        scope: RUN_TIME
        value: "sqlite:///app.db"
      - key: PYTHONPATH
        scope: RUN_AND_BUILD_TIME
        value: /app
      - key: FLASK_ENV
        scope: RUN_TIME
        value: production
      - key: CORS_ORIGINS
        scope: RUN_TIME
        value: "*"
    
    health_check:
      http_path: /api/health
      initial_delay_seconds: 30
      period_seconds: 10
      timeout_seconds: 5
      
    http_port: 80
    instance_count: 1
    instance_size_slug: basic-xxs
    
    routes:
      - path: /api
        preserve_path_prefix: false

# Static site configuration for Angular frontend
static_sites:
  - name: frontend-app
    source_dir: endless-gaming-frontend
    github:
      repo: tomneyland/endless-gaming
      branch: master
      deploy_on_push: true
    environment_slug: node-js
    
    build_command: |
      chmod +x .do/build.sh
      .do/build.sh
    
    output_dir: dist/endless-gaming-frontend/browser
    index_document: index.html
    catchall_document: index.html
    
    routes:
      - path: /


