"""Add storefront_data table

Revision ID: 576cf0b726eb
Revises: 3e5641233645
Create Date: 2025-07-25 18:58:59.257029

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '576cf0b726eb'
down_revision: Union[str, Sequence[str], None] = '3e5641233645'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('storefront_data',
    sa.Column('app_id', sa.Integer(), nullable=False),
    sa.Column('short_description', sa.Text(), nullable=True),
    sa.Column('detailed_description', sa.Text(), nullable=True),
    sa.Column('is_free', sa.Boolean(), nullable=True),
    sa.Column('required_age', sa.Integer(), nullable=True),
    sa.Column('website', sa.String(), nullable=True),
    sa.Column('header_image', sa.String(), nullable=True),
    sa.Column('release_date', sa.String(), nullable=True),
    sa.Column('developers', sa.JSON(), nullable=True),
    sa.Column('publishers', sa.JSON(), nullable=True),
    sa.Column('genres', sa.JSON(), nullable=True),
    sa.Column('categories', sa.JSON(), nullable=True),
    sa.Column('supported_languages', sa.Text(), nullable=True),
    sa.Column('price_overview', sa.JSON(), nullable=True),
    sa.Column('pc_requirements', sa.JSON(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=False),
    sa.Column('fetch_attempts', sa.Integer(), server_default='0', nullable=False),
    sa.Column('fetch_status', sa.String(), server_default='pending', nullable=False),
    sa.ForeignKeyConstraint(['app_id'], ['games.app_id'], ),
    sa.PrimaryKeyConstraint('app_id')
    )
    op.create_index(op.f('ix_storefront_data_app_id'), 'storefront_data', ['app_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_storefront_data_app_id'), table_name='storefront_data')
    op.drop_table('storefront_data')
    # ### end Alembic commands ###
