"""Add screenshots and movies to storefront_data

Revision ID: cdf2c58c0747
Revises: 576cf0b726eb
Create Date: 2025-07-25 19:27:05.898457

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cdf2c58c0747'
down_revision: Union[str, Sequence[str], None] = '576cf0b726eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('storefront_data', sa.Column('screenshots', sa.JSON(), nullable=True))
    op.add_column('storefront_data', sa.Column('movies', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('storefront_data', 'movies')
    op.drop_column('storefront_data', 'screenshots')
    # ### end Alembic commands ###
