"""Initial migration

Revision ID: ed71d7394c09
Revises: 
Create Date: 2025-07-19 20:34:45.607635

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed71d7394c09'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('games',
    sa.Column('app_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('app_id')
    )
    op.create_index(op.f('ix_games_app_id'), 'games', ['app_id'], unique=False)
    op.create_index(op.f('ix_games_name'), 'games', ['name'], unique=False)
    op.create_table('game_metadata',
    sa.Column('app_id', sa.Integer(), nullable=False),
    sa.Column('developer', sa.String(), nullable=True),
    sa.Column('publisher', sa.String(), nullable=True),
    sa.Column('owners_estimate', sa.String(), nullable=True),
    sa.Column('positive_reviews', sa.Integer(), nullable=True),
    sa.Column('negative_reviews', sa.Integer(), nullable=True),
    sa.Column('score_rank', sa.Integer(), nullable=True),
    sa.Column('average_playtime_forever', sa.Integer(), nullable=True),
    sa.Column('average_playtime_2weeks', sa.Integer(), nullable=True),
    sa.Column('price', sa.String(), nullable=True),
    sa.Column('genre', sa.String(), nullable=True),
    sa.Column('languages', sa.Text(), nullable=True),
    sa.Column('tags_json', sa.JSON(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=False),
    sa.Column('fetch_attempts', sa.Integer(), server_default='0', nullable=False),
    sa.Column('fetch_status', sa.String(), server_default='pending', nullable=False),
    sa.ForeignKeyConstraint(['app_id'], ['games.app_id'], ),
    sa.PrimaryKeyConstraint('app_id')
    )
    op.create_index(op.f('ix_game_metadata_app_id'), 'game_metadata', ['app_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_game_metadata_app_id'), table_name='game_metadata')
    op.drop_table('game_metadata')
    op.drop_index(op.f('ix_games_name'), table_name='games')
    op.drop_index(op.f('ix_games_app_id'), table_name='games')
    op.drop_table('games')
    # ### end Alembic commands ###
